name: ci-build
on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  # Build dependencies
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - name: Validate composer.json and composer.lock
#        run: composer install --strict

#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v3
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint PHP files
        run: composer phpcs

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Security scan
        run: composer security:check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run PHPUnit
        run: php bin/phpunit

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - name: Validate composer.json and composer.lock
#        run: composer validate

      - name: Deploy to production
        run: echo "Deploying to production"
